before:
  hooks:
    - go mod tidy
builds:
  - id: pigps
    binary: pigps
    main: ./cmd/pigps
    goos:
      - linux
    goarch:
      - arm
      - arm64
archives:
  - format: binary
    replacements:
      arm64: arm64
      arm: arm32
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Arch }}"
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
