version: 2
before:
  hooks:
    - go mod tidy
builds:
  - id: pigps
    binary: pigps
    main: ./cmd/pigps
    goos:
      - linux
    goarch:
      - arm
      - arm64
archives:
  - formats:
      - binary
    name_template: >-
      {{ .Binary }}_{{ .Version }}_
      {{- if eq .Arch "arm" }}arm32
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
